FROM python:3.10-slim

# Instalar solo lo necesario
RUN apt-get update && apt-get install -y --no-install-recommends \
    chromium \
    chromium-driver \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Usuario no root por seguridad
RUN useradd -m botuser
USER botuser

COPY . .
CMD ["python", "app.py"]